version: "3.8"

services:
  opensearch:
    image: opensearchproject/opensearch:2.17.0
    container_name: opensearch-data-agent
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Admin@123
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=false
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net:
